title = "Kris N贸va"
baseURL = 'https://krisnova.net/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

[outputs]
  home = [ "HTML", "RSS" ] # Generate RSS

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="bio"
    name = 'Bio'
    url = '/bio/'
    weight = 30

[params]
  sitename = "Kris N贸va"
  defaultColor = "dark"
  description = "Minimal Hugo blog theme with light and dark mode support"

[params.author]
  avatar = "img/nova.jpg"
  intro = "Kris N贸va"
  name = "Kris N贸va"
  description = "Complete Technical Works"