title = "Kris Nóva"
baseURL = 'https://krisnova.net/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

[outputs]
  home = [ "HTML", "RSS" ] # Generate RSS

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="tech"
    name = 'Tech'
    url = '/tech/'
    weight = 20
  [[menu.main]]
    pageRef="bio"
    name = 'Bio'
    url = '/bio/'
    weight = 30

[params]
  sitename = "Kris Nóva"
  defaultColor = "dark"
  description = "Complete technical works and social posts of alpinist, software engineer, and computer scientist Kris Nóva. Compute runtime, Linux, Aurae, Kubernetes, Security, and Kernel topics. Distributed systems. Cyber Security. Analysis. Math."

[params.author]
  avatar = "img/nova.jpg"
  intro = "Kris Nóva"
  name = "Kris Nóva"
  description = "Complete Technical Works"